# 開発用

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.dockerfile
    tty: true
    ports:
      - 10000:10000
    depends_on:
      - db
    volumes:
      - .:/app

  postgresql:
    image: postgres:13.3
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "seasonalfood"
    ports:
      - "5432:5432"
    networks:
      - default

networks:
  default:

volumes:
  # mysql_data:
  postgresql-data:
# # 本番用
# services:
#   app:
#     container_name: app
#     build:
#       context: .
#       dockerfile: app.dockerfile
#     tty: true
#     ports:
#       - 8023:8023
#     depends_on:
#       - db
#     volumes:
#       - .:/app

#   db:
#     container_name: db
#     build:
#       context: .
#       dockerfile: db.dockerfile
#     tty: true
#     ports:
#       - 3305:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: "root"
#       MYSQL_DATABASE: "test"
#       MYSQL_USER: "tester"
#       MYSQL_PASSWORD: "password"
#     volumes:
#       - type: volume
#         source: mysql_data
#         target: /var/lib/mysql
#     networks:
#       - default
#   phpmyadmin:
#     container_name: phpmyadmin
#     image: phpmyadmin
#     depends_on:
#       - db
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOSTS=db
#       - PMA_USER=root
#       - PMA_PASSWORD=root
#     ports:
#       - "3001:80"

# networks:
#   default:

# volumes:
#   mysql_data:
