# 開発用

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app.dockerfile
    tty: true
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.dockerfile
    tty: true
    command: >
      bash -c '
      touch /tmp/mysql.log &&
      tail -f /tmp/mysql.log &
      /usr/local/bin/docker-entrypoint.sh mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general-log=true
      --general-log-file=/tmp/mysql.log
      '
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "password"
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    networks:
      - default
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3001:80"

networks:
  default:

volumes:
  mysql_data:
# # 本番用
# services:
#   app:
#     container_name: app
#     build:
#       context: .
#       dockerfile: app.dockerfile
#     tty: true
#     ports:
#       - 8023:8023
#     depends_on:
#       - db
#     volumes:
#       - .:/app

#   db:
#     container_name: db
#     build:
#       context: .
#       dockerfile: db.dockerfile
#     tty: true
#     ports:
#       - 3305:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: "root"
#       MYSQL_DATABASE: "test"
#       MYSQL_USER: "tester"
#       MYSQL_PASSWORD: "password"
#     volumes:
#       - type: volume
#         source: mysql_data
#         target: /var/lib/mysql
#     networks:
#       - default
#   phpmyadmin:
#     container_name: phpmyadmin
#     image: phpmyadmin
#     depends_on:
#       - db
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOSTS=db
#       - PMA_USER=root
#       - PMA_PASSWORD=root
#     ports:
#       - "3001:80"

# networks:
#   default:

# volumes:
#   mysql_data:
